config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get 'home/about' => 'homes#about', as: 'about'

  get 'search' => 'searches#search'

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords'
  }

  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] # :book_id :id　＝＞　/books/:book_id/book_comments/:id
  end

  resources :rooms, only: [:create]
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: :index

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :body, presence: true, length: {maximum: 150}

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.build(book_comment_params)
    @book_comment.book_id = @book.id
    if @book_comment.save
      @comments = @book.book_comments.order(created_at: :desc)
      render :index
      # @book_comments = @book.book_comments.order(created_at: :desc)
      # redirect_back(fallback_location: root_path)
    else
      # @newbook = Book.new
      # @user = current_user
      # @book_comment = BookComment.new
      render "error"
    end
  end

  def destroy
    # /books/:book_id/book_comments/:id
    @book_comment = BookComment.find(params[:id])
    if @book_comment.user == current_user
       @book_comment.destroy
       render :destroy
      # redirect_back(fallback_location: root_path)
    else
       redirect_to books_path
    end
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:body)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_count.html.erb
<span>コメント数:　</span>
	<%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
      <%= form_with(model:[book, book_comment], url: book_book_comments_path(book), remote: true ) do |f| %>
				<div class="row">
					<div class="col-sm-12">
						<%= f.text_area :body, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
					</div>
				</div>
				<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>

app/views/book_comments/_index.html.erb
				<% comments.each do |comment| %>
					<li id="comment-<%= comment.id %>" style="margin-bottom: 30px;">
						<div class="comment-body bb">
							<div class="comment-avatar">
								<div class="avatar">
									<%= attachment_image_tag comment.user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg" %>
								</div>
							</div>
							<div class="comment-text">
								<div class="comment-author clearfix">
									<%= comment.user.name %>
									<span class="comment-meta">
										<span class="comment-date">
											<%= comment.created_at.strftime('%Y/%m/%d') %>
										</span>
									</span>
								</div>
								<div class="comment-entry">
									<%= comment.body %>
								</div>
								<span class="delete-button">
									<% if comment.user == current_user %>
										<%= link_to "削除", book_book_comment_path(book.id, comment.id), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
									<% end %>
								</span>
							</div>
						</div>
					</li>
				<% end %>

app/views/book_comments/create.html.erb
<h1>BookComments#create</h1>
<p>Find me in app/views/book_comments/create.html.erb</p>

app/views/book_comments/destroy.html.erb
<h1>BookComments#destroy</h1>
<p>Find me in app/views/book_comments/destroy.html.erb</p>

app/views/book_comments/destroy.js.erb
$('#comment-<%= @book_comment.id %>').remove();
$("#comments_count").html("<%= j(render 'count', { book: @book_comment.book }) %>")

app/views/book_comments/error.js.erb
$("#comments_error").prepend("<%= j(render 'layouts/errors', { model: @book_comment }) %>")

app/views/book_comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comments, book: @book }) %>")
$("#comments_count").html("<%= j(render 'count', { book: @book }) %>")
$("textarea").val('')