config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#top'

  get 'home/about' => 'homes#about', as: 'about'

  get 'search' => 'searches#search'

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords'
  }

  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy] # :book_id :id　＝＞　/books/:book_id/book_comments/:id
  end

  resources :rooms, only: [:create]
  get 'chat/:id' => 'chats#show', as: 'chat'
  resources :chats, only: [:create]

  resources :notifications, only: :index

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	has_many :favorites, dependent: :destroy

	has_many :book_comments, dependent: :destroy
	
	has_many :notifications, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def self.search(search, word)
		if search == "perfect_match"
			@book = Book.where(title: "#{word}")
		elsif search == "forward_match"
			@book = Book.where("title LIKE?","#{word}%")
		elsif search == "backward_match"
			@book = Book.where("title LIKE?","%#{word}")
		elsif search == "partial_match"
			@book = Book.where("title LIKE?","%#{word}%")
		else
			@book = Book.all
		end
	end
	
	def create_notification_by(current_user)
		notification = current_user.active_notifications.new(
			book_id: id,
			visited_id: user_id,
			action: "favorite"
		)
		notification.save if notification.valid?
	end
	
	def create_notification_comment!(current_user, book_comment_id)
		temp_ids = BookComment.select(:user_id).where(book_id: id).where.not(user_id: current_user.id).distinct
		temp_ids.each do |temp_id|
			save_notification_comment!(current_user, book_comment_id, temp_id['user_id'])
		end
		save_notification_comment!(current_user, book_comment_id, user_id) if temp_ids.blank?
	end
	
	def save_notification_comment!(current_user, book_comment_id, visited_id)
		notification = current_user.active_notifications.new(
			book_id: id,
			book_comment_id: book_comment_id,
			visited_id: visited_id,
			action: 'book_comment'
		)
		if notification.visiter_id == notification.visited_id
			notification.checked = true
		end
		notification.save if notification.valid?
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
    @book_comments = @book.book_comments.order(created_at: :desc)
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>

  <%= render 'layouts/errors', model: f.object %>

  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/form", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<% if user_signed_in? %>
						<td>
							<div id="favorites_buttons_<%= book.id %>">
								<%= render 'favorites/favorite', book: book %>
							</div>
						</td>
						<td><span>コメント数:　</span><%= book.book_comments.count %></td>
					<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @book.user %>
		<h2>New book</h2>
		<%= render 'books/form', book: @newbook %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<td>
						<% if @book.user == current_user %>
							<%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %>
						<% end %>
					</td>
					<td>
						<% if @book.user == current_user %>
							<%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
						<% end %>
					</td>
					<% if user_signed_in? %>
						<td>
							<div id="favorites_buttons_<%= @book.id %>">
								<%= render 'favorites/favorite', book: @book %>
							</div>
						</td>
					<% end %>
					<td id="comments_count">
						<%= render 'book_comments/count', book: @book %>
					</td>
				</tr>
			</table>

			<hr>

			<ol id="comments_area">
				<%= render 'book_comments/index', comments: @book_comments, book: @book %>
			</ol>
			<hr>
			<div id="comments_error">
				<%= render 'layouts/errors', model: @book_comment %>
			</div>
			<div class="comment-create">
				<%= render 'book_comments/form', book: @book, book_comment: @book_comment %>
			</div>

	</div>
</div>